######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 5 11:12:51 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += rgbhsv_qt.ui
